{"uuid": "45b5d52f-ffb8-4eb3-b87a-47563c2a468a", "children": ["d2ed671a-b576-44b5-95f7-8cc0321b8cf4"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "RuntimeError: 浏览器启动失败: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0xccfd23+62915]\n\tGetHandleVerifier [0x0xccfd64+62980]\n\t(No symbol) [0x0xb03e13]\n\t(No symbol) [0x0xb378e8]\n\t(No symbol) [0x0xb331e9]\n\t(No symbol) [0x0xb7ce32]\n\t(No symbol) [0x0xb7c74a]\n\t(No symbol) [0x0xb711d6]\n\t(No symbol) [0x0xb40833]\n\t(No symbol) [0x0xb416a4]\n\tGetHandleVerifier [0x0xf38d13+2590131]\n\tGetHandleVerifier [0x0xf33f5a+2570234]\n\tGetHandleVerifier [0x0xcf59da+217722]\n\tGetHandleVerifier [0x0xce6048+153832]\n\tGetHandleVerifier [0x0xcec4ad+179533]\n\tGetHandleVerifier [0x0xcd7728+94152]\n\tGetHandleVerifier [0x0xcd78b2+94546]\n\tGetHandleVerifier [0x0xcc2bca+9322]\n\tBaseThreadInitThunk [0x0x75fb5d49+25]\n\tRtlInitializeExceptionChain [0x0x7777d1ab+107]\n\tRtlGetAppContainerNamedObjectPath [0x0x7777d131+561]\n\n", "trace": "  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\pytest_asyncio\\plugin.py\", line 681, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\tests\\conftest.py\", line 23, in browser\n    driver = manager.start_browser()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\core\\browser_manager.py\", line 110, in start_browser\n    raise RuntimeError(f\"浏览器启动失败: {str(e)}\")\n"}, "start": 1754985529787, "stop": 1754985550461}], "start": 1754985529787, "stop": 1754985550611}