{"uuid": "d7a55639-bd34-4c33-97a6-bdb13c2604c8", "children": ["4b877c65-ee78-47bf-af1c-650a0365a0a4"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "RuntimeError: 浏览器启动失败: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0x6afd23+62915]\n\tGetHandleVerifier [0x0x6afd64+62980]\n\t(No symbol) [0x0x4e3e13]\n\t(No symbol) [0x0x5178e8]\n\t(No symbol) [0x0x5131e9]\n\t(No symbol) [0x0x55ce32]\n\t(No symbol) [0x0x55c74a]\n\t(No symbol) [0x0x5511d6]\n\t(No symbol) [0x0x520833]\n\t(No symbol) [0x0x5216a4]\n\tGetHandleVerifier [0x0x918d13+2590131]\n\tGetHandleVerifier [0x0x913f5a+2570234]\n\tGetHandleVerifier [0x0x6d59da+217722]\n\tGetHandleVerifier [0x0x6c6048+153832]\n\tGetHandleVerifier [0x0x6cc4ad+179533]\n\tGetHandleVerifier [0x0x6b7728+94152]\n\tGetHandleVerifier [0x0x6b78b2+94546]\n\tGetHandleVerifier [0x0x6a2bca+9322]\n\tBaseThreadInitThunk [0x0x75fb5d49+25]\n\tRtlInitializeExceptionChain [0x0x7777d1ab+107]\n\tRtlGetAppContainerNamedObjectPath [0x0x7777d131+561]\n\n", "trace": "  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\pytest_asyncio\\plugin.py\", line 681, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\tests\\conftest.py\", line 23, in browser\n    driver = manager.start_browser()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\core\\browser_manager.py\", line 110, in start_browser\n    raise RuntimeError(f\"浏览器启动失败: {str(e)}\")\n"}, "start": 1754984820026, "stop": 1754984840378}], "start": 1754984820026, "stop": 1754984840485}