{"uuid": "7a394951-03a9-44bf-9757-ae0991af832f", "children": ["503926a5-0068-4d2d-a3c1-38220b83f0f7"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "RuntimeError: 浏览器启动失败: Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir\nStacktrace:\n\tGetHandleVerifier [0x0x9aba83+63395]\n\tGetHandleVerifier [0x0x9abac4+63460]\n\t(No symbol) [0x0x7f2113]\n\t(No symbol) [0x0x8258b8]\n\t(No symbol) [0x0x8211a9]\n\t(No symbol) [0x0x86ae57]\n\t(No symbol) [0x0x86a74a]\n\t(No symbol) [0x0x85f1a6]\n\t(No symbol) [0x0x82e7b2]\n\t(No symbol) [0x0x82f654]\n\tGetHandleVerifier [0x0xc28883+2672035]\n\tGetHandleVerifier [0x0xc23cba+2652634]\n\tGetHandleVerifier [0x0x9d2bca+223466]\n\tGetHandleVerifier [0x0x9c2cb8+158168]\n\tGetHandleVerifier [0x0x9c978d+185517]\n\tGetHandleVerifier [0x0x9b3b78+96408]\n\tGetHandleVerifier [0x0x9b3d02+96802]\n\tGetHandleVerifier [0x0x99e90a+9770]\n\tBaseThreadInitThunk [0x0x76ff5d49+25]\n\tRtlInitializeExceptionChain [0x0x7786d1ab+107]\n\tRtlGetAppContainerNamedObjectPath [0x0x7786d131+561]\n\n", "trace": "  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\pytest_asyncio\\plugin.py\", line 681, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\Python312-32\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\tests\\conftest.py\", line 9, in browser\n    driver = browser.start_browser()\n             ^^^^^^^^^^^^^^^^^^^^^^^\n  File \"D:\\project_selenium_improve\\core\\browser_manager.py\", line 122, in start_browser\n    raise RuntimeError(f\"浏览器启动失败: {str(e)}\")\n"}, "start": 1754637877129, "stop": 1754637924801}], "start": 1754637877129, "stop": 1754637924902}